apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-pass
               key: password
         - name: MYSQL_DATABASE
           valueFrom:
             secretKeyRef:
               name: mysql-pass
               key: databaseName
	 - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               name: mysql-pass
               key: username
        ports:
        - containerPort: 3306
          name: mysql
