apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: RGhhcm1lbmRyYQ==   #Dharmendra 
  username: RGhhcm1lbmRyYQ==   #Dharmendra
  databaseName: RGhhcm1lbmRyYQ==  #Dharmendra
